dist: xenial
cache:
  directories:
    - $HOME/.cache/pip

language: python

matrix:
  fast_finish: true

  include:
    # Meta
    - python: "3.7"
      env: NOXSESSION="lint"
    - python: "3.7"
      env: NOXSESSION="doc"

install:
  - pip install -U nox

script:
  - nox --non-interactive --session "$NOXSESSION"

notifications:
  email: false
